import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
// import "./styke2.css"

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
